### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Johnyyyyx** [0xdln1/dorker#1]
python dorker.py -f 1.txt

    ______ ___________ _   __ ___________ 
    |  _  \  _  | ___ \ | / /|  ___| ___ |
    | | | | | | | |_/ / |/ / | |__ | |_/ /
    | | | | | | |    /|    \ |  __||    / 
    | |/ /\ \_/ / |\ \| |\  \| |___| |\ \ 
    |___/  \___/\_| \_\_| \_/\____/\_| \_|             

        Created by @0xdln and @0xrj
    
Traceback (most recent call last):
  File "/home/kali/Desktop/dorker-main/dorker.py", line 132, in <module>
    main()
  File "/home/kali/Desktop/dorker-main/dorker.py", line 120, in main
    exechaha(args,dorks)
  File "/home/kali/Desktop/dorker-main/dorker.py", line 104, in exechaha
    flow()
  File "/home/kali/Desktop/dorker-main/dorker.py", line 83, in flow
    urlExtract()
  File "/home/kali/Desktop/dorker-main/dorker.py", line 60, in urlExtract
    re_enter()
  File "/home/kali/Desktop/dorker-main/dorker.py", line 50, in re_enter
    go_to(prev_url)
  File "/home/kali/.local/lib/python3.10/site-packages/helium/__init__.py", line 152, in go_to
    _get_api_impl().go_to_impl(url)
  File "/home/kali/.local/lib/python3.10/site-packages/helium/_impl/__init__.py", line 37, in f_decorated
    result = f(self, *args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/helium/_impl/__init__.py", line 56, in f_decorated
    return f(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/helium/_impl/__init__.py", line 157, in go_to_impl
    if '://' not in url:
TypeError: argument of type 'int' is not iterable

**Comment by 1nfam0ux** [comment]
same error has above , any idea ??

**Comment by 0xdln1** [comment]
Hi, Can u give more details about the issue, like what are the contents in file `1.txt` ? @Johnyyyyx  @1nfam0ux

**Comment by 1nfam0ux** [comment]
can't see file 1.txt in folder " Dorker-main " , where will this file be @0xdln1 

i was going to try on ubuntu and see if it has to do with parrot OS in my case or kali in @Johnyyyyx case , because from my debuging it might have to do with the geckodriver , ill update once i crosscheck , because running geckodriver -V i get errors on ParrotOS because firefox is replaced
`Package firefox is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  parrot-interface-common`

**Comment by 1nfam0ux** [comment]
@Johnyyyyx i can confirm that the first initial error you reported is due to the geckodriver , confirm your geckodriver is properly installed or follow this [install geckodriver](https://www.cyberithub.com/how-to-install-geckodriver-for-selenium-in-linux/)

@0xdln1 now the new error is get is this 
`dorker-main$ python3 dorker.py -d 'inurl:dork'
Traceback (most recent call last):
  File "/home/systemctl/Set/dorker-main/dorker.py", line 3, in <module>
    from helium import *
ModuleNotFoundError: No module named 'helium'
`

also whats this extra parameter i saw in your example "python3 dorker.py -d 'DORK FOR XSS PARAMS' | dalfox". thanks for help

**Comment by 0xdln1** [comment]
Hi @1nfam0ux , the file `1.txt` can be any file which is having dorks, for example 

![image](https://user-images.githubusercontent.com/83292788/207020354-b891f6e7-0b3b-4b99-b270-dd6e48b85d1b.png)

I see you have not installed helium module in python, you can do that by `pip3 install -r requirements.txt`
And before trying to run this tool, install all requirements, See https://github.com/0xdln1/dorker#installation for detailed instruction steps

**Comment by 1nfam0ux** [comment]
ok , if you like i can write a full explainer , incase others have this issues.. Installing all the requirement fixed all errors . thanks for your time , you on patreon or jabber @0xdln1  ?

**Comment by 0xdln1** [comment]
Hi @1nfam0ux sure if you would like to write a detailed help page, go ahead, send a pr with the changes. No i am not on patreon or jabber, but i am on buymeacoffee at https://www.buymeacoffee.com/0xdln .

**Comment by 0xdln1** [comment]
Closing this issue as this is solved :)

**Comment by 0xdln1** [comment]
Closed
